# the index of the site
index = "README.md"
# skeleton for markdown
skeleton = "skeleton.html"

# the repo settings
[git]
# url of the repo
url = "https://github.com/Dawidkubis/python-gjk.git"
# branch of the repo
branch = "master"

