# the index of the site
index = "README.md"
# skeleton for markdown
skeleton = "skeleton.html"

# the repo settings
[git]
# url of the repo
url = "<your git repository url>"
# branch of the repo
branch = "master"

