# the index of the site
index = "README.md"
# skeleton for markdown
skeleton = "skeleton.html"
# ad-hoc settings
response = "responses.toml"
# serve all the files?
serve_all = true

# the repo settings
[git]
# url of the repo
url = "https://github.com/Dawidkubis/test.git"
# branch of the repo
branch = "master"

