# the index of the site
index = "README.md"
# skeleton for markdown
skeleton = "skeleton.html"
response = "responses.toml"

# the repo settings
[git]
# url of the repo
url = "https://github.com/Dawidkubis/test.git"
# branch of the repo
branch = "master"

